export const lang = {
  APP_TITLE: "HABIT",
  CREATE_HABIT_BUTTON: "Create Habit",
  CREATE_HABIT_TITLE: "Create Habit",
  CREATE_HABIT_DESCRIPTION: "Create a new habit to track your progress.",
  HABIT_NAME_LABEL: "Habit Name",
  HABIT_NAME_PLACEHOLDER: "eg: Walk 10,000 steps",
  HABIT_DESCRIPTION_LABEL: "Question",
  HABIT_DESCRIPTION_PLACEHOLDER: "eg: Am I healthy",
  IS_MEASURABLE_LABEL: "Is it a measurable habit?",
  UNIT_LABEL: "Unit",
  UNIT_PLACEHOLDER: "eg: mile",
  TARGET_LABEL: "Target",
  TARGET_PLACEHOLDER: "eg: 50",
  TARGET_TYPE_LABEL: "Target Type",
  COLOR_LABEL: "Color",
  SUBMIT_BUTTON: "Create Habit",
  YES_OPTION: "Yes",
  NO_OPTION: "No",
  SELECT_TARGET_TYPE_PLACEHOLDER: "Select Target Type",
  NOTE_PLACEHOLDER: "Note",
  VALUE_PLACEHOLDER: "eg: 50",
  SAVE_BUTTON: "Save",
  DID_YOU_CRUSH_IT_LABEL: "Did you crush it?",
};
